version: '3'
services:
  jira:
    container_name: jira
    depends_on:
      - postgresql
    image: atlassian/jira-software:8.7.1
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8001:8080'
    environment:
      - 'ATL_JDBC_URL=postgresql:5432'
      - 'ATL_JDBC_USER=jiradbuser'
      - 'ATL_JDBC_PASSWORD=admin'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
  postgresql:
    container_name: postgres
    image: postgres:9.6
    expose:
      - '5432'
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jiradbuser'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
networks:
  jiranet:
    driver: bridge