using JiraOAuthSignatureMethod = Atlassian.Jira.OAuth.JiraOAuthSignatureMethod;

namespace JiraOauth.OAuthTokenHelper
{
    public class JiraOAuthAccessTokenSettings
    {
        /// <summary>
        /// The default relative URL to request an access token.
        /// </summary>
        public const string DefaultAccessTokenUrl = "plugins/servlet/oauth/access-token";

        /// <summary>
        /// Initializes a new instance of the <see cref="Atlassian.Jira.OAuth.OAuthAccessTokenSettings"/> class.
        /// </summary>
        /// <param name="url">The URL of the Jira instance to request to.</param>
        /// <param name="consumerKey">The consumer key provided by the Jira application link.</param>
        /// <param name="consumerSecret">The consumer private key in XML format.</param>
        /// <param name="oAuthRequestToken">The OAuth request token generated by Jira.</param>
        /// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
        /// <param name="oAuthVerifier">TODO</param>
        /// <param name="signatureMethod">The signature method used to sign the request.</param>
        /// <param name="accessTokenUrl">The relative URL to request the access token to Jira.</param>
        public JiraOAuthAccessTokenSettings(
            string url,
            string consumerKey,
            string consumerSecret,
            string oAuthRequestToken,
            string oAuthTokenSecret,
            string oAuthVerifier,
            JiraOAuthSignatureMethod signatureMethod = JiraOAuthSignatureMethod.RsaSha1,
            string accessTokenUrl = DefaultAccessTokenUrl)
        {
            Url = url;
            ConsumerKey = consumerKey;
            ConsumerSecret = consumerSecret;
            OAuthRequestToken = oAuthRequestToken;
            OAuthTokenSecret = oAuthTokenSecret;
            OAuthVerifier = oAuthVerifier;
            SignatureMethod = signatureMethod;
            AccessTokenUrl = accessTokenUrl;
        }

        /// <summary>
        /// Gets the URL of the Jira instance to request to.
        /// </summary>
        public string Url { get; }

        /// <summary>
        /// Gets the consumer key provided by the Jira application link.
        /// </summary>
        public string ConsumerKey { get; }

        /// <summary>
        /// Gets the consumer private key in XML format.
        /// </summary>
        public string ConsumerSecret { get; }

        /// <summary>
        /// Gets the OAuth request token generated by Jira.
        /// </summary>
        public string OAuthRequestToken { get; }

        /// <summary>
        /// Gets the OAuth token secret generated by Jira.
        /// </summary>
        public string OAuthTokenSecret { get; }

        /// <summary>
        /// TODO => Missing in SDK!!!!
        /// </summary>
        public string OAuthVerifier { get; set; }

        /// <summary>
        /// Gets the signature method used to sign the request.
        /// </summary>
        public JiraOAuthSignatureMethod SignatureMethod { get; }

        /// <summary>
        /// Gets the relative URL to request the access token.
        /// </summary>
        public string AccessTokenUrl { get; }
    }
}